[info]
name = "bandwhich"
version = "0.20.0"
url = "https://github.com/imsnif/bandwhich"
licence = "MIT"

[discover]
binary = "bandwhich"
version_check.args = ["--version"]
version_check.pattern = "bandwhich (\\d\\S+)"

[[install]]
download = "https://github.com/imsnif/bandwhich/releases/download/0.20.0/bandwhich-v0.20.0-x86_64-unknown-linux-musl.tar.gz"
checksums.b2 = "e5562f3a6fc8876773020b1bf9ea5ea94b5740156de0165da5f0dc3550fe8595f70d12d6b46815b80068db0e7d5eb5f1e9918c63a6b2d20b86c5aa496ab6dcb7"
files = [
    { source = "bandwhich", type = "bin" },
]

[[install]]
download = "https://github.com/imsnif/bandwhich/archive/0.20.0.tar.gz"
checksums.b2 = "d2809660b09d1b02bbf8b2b8719406b49064275202af422fc32fa2add34ffc04d748073b6a51c827662418292c0e10c0aa3ca3955e5317e3a0015c25e15755ec"
files = [
    { source = "bandwhich-0.20.0/docs/bandwhich.1", type = "man", section = 1 },
]
