[info]
name = "bandwhich"
version = "0.15.0"
url = "https://github.com/imsnif/bandwhich"
licence = "MIT"

[discover]
binary = "bandwhich"
version_check.args = ["--version"]
version_check.pattern = "bandwhich (\\d\\S+)"

[[install]]
download = "https://github.com/imsnif/bandwhich/releases/download/0.15.0/bandwhich-v0.15.0-x86_64-unknown-linux-musl.tar.gz"
checksums.b2 = "c57c6d1856e5554f4d33583f73ddcc35ddebbd4f552b62e742e3fd4cf5b73abdec6d1fec549e4ed433178b44fc6fc59c94675f2d3782ad882756f8364aee58ec"
files = [
    { source = "bandwhich", type = "bin" },
]

[[install]]
download = "https://github.com/imsnif/bandwhich/archive/0.15.0.tar.gz"
checksums.b2 = "5daf3e994d723ab16202a9dbb6fa5f246a5ee73bb7cfc0ee71ef1d6e463196c1a6c8e34575b23a11f11b02a710a014f6e683029960a8ee6a382360a174c92ecf"
files = [
    { source = "bandwhich-0.15.0/docs/bandwhich.1", type = "man", section = 1 },
]
