[info]
name = "bat"
version = "0.16.0"
url = "https://github.com/sharkdp/bat"
license = "MIT OR Apache-2.0"

[discover]
binary = "bat"
version_check.args = ["--version"]
version_check.pattern = "bat (\\d\\S+)"

[[install]]
download = "https://github.com/sharkdp/bat/releases/download/v0.16.0/bat-v0.16.0-x86_64-unknown-linux-musl.tar.gz"
checksums.b2 = "a709e601a4b0a0ab712d31d18559a0975ebc80c6beb7088262e4e331a4bb5cb6e39315316182571db7cba0b34e1cac91c2d1f1cd5ec9faac0bf4b53bf362a554"
files = [
    { source = "bat-v0.16.0-x86_64-unknown-linux-musl/bat", type = "bin" },
    { source = "bat-v0.16.0-x86_64-unknown-linux-musl/bat.1", type = "manpage", section = 1 },
    { source = "bat-v0.16.0-x86_64-unknown-linux-musl/autocomplete/bat.fish", type = "completion", shell = "fish" }
]
