[info]
name = "bat"
version = "0.17.1"
url = "https://github.com/sharkdp/bat"
license = "MIT OR Apache-2.0"

[discover]
binary = "bat"
version_check.args = ["--version"]
version_check.pattern = "bat (\\d\\S+)"

[[install]]
download = "https://github.com/sharkdp/bat/releases/download/v0.17.1/bat-v0.17.1-x86_64-unknown-linux-musl.tar.gz"
checksums.b2 = "865ba61124abc527b30cfcd92a32fd8708255c49859681c39d41b12011df9609b2522adecd5dbab33e0de7ec13cf67bb883ce42451ea5c0ebbc5640cae09bfad"
files = [
    { source = "bat-v0.17.1-x86_64-unknown-linux-musl/bat", type = "bin" },
    { source = "bat-v0.17.1-x86_64-unknown-linux-musl/bat.1", type = "manpage", section = 1 },
    { source = "bat-v0.17.1-x86_64-unknown-linux-musl/autocomplete/bat.fish", type = "completion", shell = "fish" }
]
