[info]
name = "coursier"
url = "https://get-coursier.io"
version = "2.0.9"
license = "Apache-2.0"

[discover]
binary = "cs"
version_check.args = ["--version"]
version_check.pattern = "(\\S+)"

[[install]]
download = "https://github.com/coursier/coursier/releases/download/v2.0.9/cs-amd64-pc-linux"
checksums.b2 = "85be5578380da4c9873f88c668c65ed57e65f99cba31770d46b6ba741e7ba68866c4bfe648eba010e6e69f500f25fe7f1069c93ced593c5e836f1b944f486da5"
name = "cs"
type = "bin"
