[info]
name = "docker-credential-secretservice"
version = "0.6.3"
url = "https://github.com/docker/docker-credential-helpers"
license = "MIT"

[discover]
binary = "docker-credential-secretservice"
version_check.args = ["version"]
version_check.pattern = "(\\d\\S+)"

[[install]]
download = "https://github.com/docker/docker-credential-helpers/releases/download/v0.6.3/docker-credential-secretservice-v0.6.3-amd64.tar.gz"
checksums.b2 = "a9fb960651122f8fdb20d594de0781cfa8445ad4fda4951ed115f93a56724929b3758a6d171492f2d9855b1c959c355d3eb9f0e8793addd6229468d5b8d8ef2b"
files = [
    { source = "docker-credential-secretservice", type = "bin" }
]
