[info]
name = "gh"
version = "1.4.0"
url = "https://cli.github.com/"
license = "MIT"

[discover]
binary = "gh"
version_check.args = ["--version"]
version_check.pattern = "gh version (\\d\\S+)"

[[install]]
download = "https://github.com/cli/cli/releases/download/v1.4.0/gh_1.4.0_linux_amd64.tar.gz"
checksums.sha256 = "bea14d3f99da06ac4c1d162f80345fb5c094202130d799e1a5fab3e629edbaa6"
files = [
  { source = "gh_1.4.0_linux_amd64/bin/gh", type = "binary" },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-alias-delete.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-alias-list.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-alias-set.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-alias.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-api.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-auth-login.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-auth-logout.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-auth-refresh.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-auth-status.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-auth.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-completion.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-config-get.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-config-set.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-config.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-gist-create.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-gist-delete.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-gist-edit.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-gist-list.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-gist-view.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-gist.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-issue-close.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-issue-create.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-issue-list.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-issue-reopen.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-issue-status.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-issue-view.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-issue.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-pr-checkout.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-pr-checks.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-pr-close.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-pr-create.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-pr-diff.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-pr-list.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-pr-merge.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-pr-ready.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-pr-reopen.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-pr-review.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-pr-status.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-pr-view.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-pr.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-release-create.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-release-delete.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-release-download.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-release-list.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-release-upload.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-release-view.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-release.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-repo-clone.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-repo-create.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-repo-fork.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-repo-view.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-repo.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-secret-list.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-secret-remove.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-secret-set.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh-secret.1", type = "man", section = 1 },
  { source = "gh_1.4.0_linux_amd64/share/man/man1/gh.1", type = "man", section = 1 },

]
