[info]
name = "git-gone"
version = "0.3.7"
url = "https://github.com/lunaryorn/git-gone"
license = "Apache-2.0"

[discover]
binary = "git-gone"
version_check.args = ["--version"]
version_check.pattern = "git-gone (\\d\\S+)"

[[install]]
download = "https://github.com/lunaryorn/git-gone/releases/download/v0.3.7/git-gone-v0.3.7-x86_64-unknown-linux-musl.tar.gz"
checksums.b2 = "0fce62d495d3991c3efe0407efaf908eb3290aeb7ba3335f8c3707da96343a2decea3a2bc53f43d0fe1ae02de3cbbfafee242ee35dc07035d240e55d795c787c"
files = [
    { source = "git-gone-v0.3.7-x86_64-unknown-linux-musl/git-gone", type = "binary" },
    { source = "git-gone-v0.3.7-x86_64-unknown-linux-musl/git-gone.1", type = "man", section = 1 },
]
