[info]
name = "git-gone"
version = "0.3.3"
url = "https://github.com/lunaryorn/git-gone"
license = "Apache-2.0"

[discover]
binary = "git-gone"
version_check.args = ["--version"]
version_check.pattern = "git-gone (\\d\\S+)"

[[install]]
download = "https://github.com/lunaryorn/git-gone/releases/download/v0.3.3/git-gone-v0.3.3-x86_64-unknown-linux-musl.tar.gz"
checksums.b2 = "bbd69ba8b353e7bd638f6eefb337da80530d384c6d1859a6a55fb7eab64966218ad4ea08d2f1249c2a1f2e868b8a1e4897ef3881634cf5a8d1f2ed0a5c047fdd"
files = [
    { source = "git-gone-v0.3.3-x86_64-unknown-linux-musl/git-gone", type = "binary" },
    { source = "git-gone-v0.3.3-x86_64-unknown-linux-musl/git-gone.1", type = "man", section = 1 },
]
