[info]
name = "git-gone"
version = "0.3.6"
url = "https://github.com/lunaryorn/git-gone"
license = "Apache-2.0"

[discover]
binary = "git-gone"
version_check.args = ["--version"]
version_check.pattern = "git-gone (\\d\\S+)"

[[install]]
download = "https://github.com/lunaryorn/git-gone/releases/download/v0.3.6/git-gone-v0.3.6-x86_64-unknown-linux-musl.tar.gz"
checksums.b2 = "3e0a2827daaafaef4acf6417b0c6486f91d113b5039bbfe27b6e6a99e76c2b3bb9e3fe53505f4597523b954738c6fb8cdb9fdea9c94ef40fc227bd4739fe3e84"
files = [
    { source = "git-gone-v0.3.6-x86_64-unknown-linux-musl/git-gone", type = "binary" },
    { source = "git-gone-v0.3.6-x86_64-unknown-linux-musl/git-gone.1", type = "man", section = 1 },
]
