[info]
name = "glab"
url = "https://github.com/profclems/glab"
version = "1.12.1"
license = "MIT"

[discover]
binary = "glab"
version_check.args = ["--version"]
version_check.pattern = "glab version (\\d\\S+)"

[[install]]
download = "https://github.com/profclems/glab/releases/download/v1.12.1/glab_1.12.1_Linux_x86_64.tar.gz"
checksums.sha256 = "478a1f450476772ec3d01d3e0c3db2435649c9997147847bd92770820382bd6d"
files = [
  { source = "glab", type = "binary" }
]
