[info]
name = "glab"
url = "https://github.com/profclems/glab"
version = "1.15.0"
license = "MIT"

[discover]
binary = "glab"
version_check.args = ["--version"]
version_check.pattern = "glab version (\\d\\S+)"

[[install]]
download = "https://github.com/profclems/glab/releases/download/v1.15.0/glab_1.15.0_Linux_x86_64.tar.gz"
checksums.sha256 = "d3d64912442c5f5d95679b41a8014a0bb29de789d3efd271b34efca9f5f33af6"
files = [
  { source = "bin/glab", type = "binary" }
]
