[info]
name = "glab"
url = "https://github.com/profclems/glab"
version = "1.14.0"
license = "MIT"

[discover]
binary = "glab"
version_check.args = ["--version"]
version_check.pattern = "glab version (\\d\\S+)"

[[install]]
download = "https://github.com/profclems/glab/releases/download/v1.14.0/glab_1.14.0_Linux_x86_64.tar.gz"
checksums.sha256 = "522b9989185c50a43f3c2c6da3028eb67d6936c8510bb05eb7909c3b6d8c4f25"
files = [
  { source = "bin/glab", type = "binary" }
]
