[info]
name = "helm"
version = "3.5.2"
url = "https://helm.sh"
license = "Apache-2.0"

[discover]
binary = "helm"
version_check.args = ["version", "--short"]
version_check.pattern = "^v(\\d\\S+)\\+"

[[install]]
download = "https://get.helm.sh/helm-v3.5.2-linux-amd64.tar.gz"
checksums.sha256 = "01b317c506f8b6ad60b11b1dc3f093276bb703281cb1ae01132752253ec706a2"
files = [
  { source = "linux-amd64/helm", type = "binary" }
]
