[info]
name = "hexyl"
version = "0.8.0"
url = "https://github.com/sharkdp/hexyl"
license = "MIT OR Apache-2.0"

[discover]
binary = "hexyl"
version_check.args = ["--version"]
version_check.pattern = "hexyl (\\d+\\S+)"

[[install]]
download = "https://github.com/sharkdp/hexyl/releases/download/v0.8.0/hexyl-v0.8.0-x86_64-unknown-linux-musl.tar.gz"
checksums.b2 = "292663185168e91bbb4c82d52a462c95af28ec4448f06dfc31e422ee8ff15d58edf2ef6b0918e5f7399aad436c910c88025a8ee8e1ef1442fdbb439e6ca4d76a"
files = [
    { source = "hexyl-v0.8.0-x86_64-unknown-linux-musl/hexyl", type = "bin" },
]
