[info]
name = "homebins"
version = "0.1.0"
url = "https://github.com/lunaryorn/homebins"
license = "MPL-2.0"

[discover]
binary = "homebins"
version_check.args = ["--version"]
version_check.pattern = "homebins (\\d\\S+)"

[[install]]
download = "https://github.com/lunaryorn/homebins/releases/download/v0.1.0/homebins-v0.1.0-x86_64-unknown-linux-musl.tar.gz"
checksums.b2 = "85a88a7f2375d17d9f0a302f4ef7d110354de2a08e2839e56eea0a0bce3200ad5eebef1e5e2709956be0ca21aecf604074bcabcd669637a0b857ed7f2c6b42a2"
files = [
    { source = "homebins-v0.1.0-x86_64-unknown-linux-musl/homebins", type = "bin" }
]
