[info]
name = "homebins"
version = "0.0.2"
url = "https://github.com/lunaryorn/homebins"
license = "MPL-2.0"

[discover]
binary = "homebins"
version_check.args = ["--version"]
version_check.pattern = "homebins (\\d\\S+)"

[[install]]
download = "https://github.com/lunaryorn/homebins/releases/download/v0.0.2/homebins-v0.0.2-x86_64-unknown-linux-musl.tar.gz"
checksums.b2 = "ec6186c25e35bc876a069a0d1915e95a4be6a2909cd182400b16bda52c142edda99496bfff85bd25fd3545868c2820792a66228ff13735d683a7e533394e3336"
files = [
    { source = "homebins-v0.0.2-x86_64-unknown-linux-musl/homebins", type = "bin" }
]
