[info]
name = "homebins"
version = "0.0.1"
url = "https://github.com/lunaryorn/homebins"
license = "MPL-2.0"

[discover]
binary = "homebins"
version_check.args = ["--version"]
version_check.pattern = "homebins (\\d\\S+)"

[[install]]
download = "https://github.com/lunaryorn/homebins/releases/download/v0.0.1/homebins-v0.0.1-x86_64-unknown-linux-musl.tar.gz"
checksums.b2 = "44862c2ce46ccf17737b44e899017ec230323034faf2b7f819d0cd4fd7ad8aee353cf07ffe263a9577ebf681a0ce9a8316b03b1b611f0c46d7f11b0e2fa841db"
files = [
    { source = "homebins-v0.0.1-x86_64-unknown-linux-musl/homebins", type = "bin" }
]
