[info]
name = "homebins"
version = "0.0.3"
url = "https://github.com/lunaryorn/homebins"
license = "MPL-2.0"

[discover]
binary = "homebins"
version_check.args = ["--version"]
version_check.pattern = "homebins (\\d\\S+)"

[[install]]
download = "https://github.com/lunaryorn/homebins/releases/download/v0.0.3/homebins-v0.0.3-x86_64-unknown-linux-musl.tar.gz"
checksums.b2 = "47c3766f9658ac411a1203f3ad2c800fc6918e1e9c978e899563f4b8935e5567498134f1e726ac623dbbe0b9816035c7df1e7648ee8764c29979e60537f8e3e9"
files = [
    { source = "homebins-v0.0.3-x86_64-unknown-linux-musl/homebins", type = "bin" }
]
