[info]
name = "homebins"
version = "0.0.1"
url = "https://github.com/lunaryorn/homebins"
license = "MPL-2.0"

[discover]
binary = "homebins"
version_check.args = ["--version"]
version_check.pattern = "homebins (\\d\\S+)"

[[install]]
download = "https://github.com/lunaryorn/homebins/releases/download/v0.0.1/homebins-v0.0.1-x86_64-unknown-linux-musl.tar.gz"
checksums.b2 = "b62b9aff4ba481543903703a8154948c6eba9bb9202a5ecbfb73f1a19de4c5ad33b28411ca172f8b2988ec19ef87faaaa3897eff048191af85d8cdddc88380b0"
files = [
    { source = "homebins-v0.0.1-x86_64-unknown-linux-musl/homebins", type = "bin" }
]
