[info]
name = "homebins"
version = "0.2.0"
url = "https://github.com/lunaryorn/homebins"
license = "MPL-2.0"

[discover]
binary = "homebins"
version_check.args = ["--version"]
version_check.pattern = "homebins (\\d\\S+)"

[[install]]
download = "https://github.com/lunaryorn/homebins/releases/download/v0.2.0/homebins-v0.2.0-x86_64-unknown-linux-musl.tar.gz"
checksums.b2 = "359cdf7775d27c68466d025c31aa53a3ed89bfad4f39364d8ee15ca155b5930210b7f75d3aafa5a2a2d4f375859063ee6efd18805d89a14767f7f40024a3b372"
files = [
    { source = "homebins-v0.2.0-x86_64-unknown-linux-musl/homebins", type = "bin" }
]
