[info]
name = "homebins"
version = "0.0.5"
url = "https://github.com/lunaryorn/homebins"
license = "MPL-2.0"

[discover]
binary = "homebins"
version_check.args = ["--version"]
version_check.pattern = "homebins (\\d\\S+)"

[[install]]
download = "https://github.com/lunaryorn/homebins/releases/download/v0.0.5/homebins-v0.0.5-x86_64-unknown-linux-musl.tar.gz"
checksums.b2 = "eed366bc66b8afc047e87fb827e3d59d663e5b465c494d2b6f3e363a3689a955baf012649b80100e919a83d8c902a50b6caa9aee384f31ae24acfee414e6afef"
files = [
    { source = "homebins-v0.0.5-x86_64-unknown-linux-musl/homebins", type = "bin" }
]
