[info]
name = "homebins"
version = "0.0.4"
url = "https://github.com/lunaryorn/homebins"
license = "MPL-2.0"

[discover]
binary = "homebins"
version_check.args = ["--version"]
version_check.pattern = "homebins (\\d\\S+)"

[[install]]
download = "https://github.com/lunaryorn/homebins/releases/download/v0.0.4/homebins-v0.0.4-x86_64-unknown-linux-musl.tar.gz"
checksums.b2 = "f7711891857cd3dad083263212e239174af50092e9cca54fa08691c31007c497287c1e4debb0b0894efe6352c15df9d483eaaba48810781453b5ec66b208d127"
files = [
    { source = "homebins-v0.0.4-x86_64-unknown-linux-musl/homebins", type = "bin" }
]
