[info]
name = "homebins"
version = "0.2.1"
url = "https://github.com/lunaryorn/homebins"
license = "MPL-2.0"

[discover]
binary = "homebins"
version_check.args = ["--version"]
version_check.pattern = "homebins (\\d\\S+)"

[[install]]
download = "https://github.com/lunaryorn/homebins/releases/download/v0.2.1/homebins-v0.2.1-x86_64-unknown-linux-musl.tar.gz"
checksums.b2 = "32c887f6038d31cee56ecc937c914fe006a244eff8a7070cb8ae218946b5301e3c7866f6f6fb932cac1ccadf91059d5ef760b8455bf9ec3cbccce395c802ebcc"
files = [
    { source = "homebins-v0.2.1-x86_64-unknown-linux-musl/homebins", type = "bin" }
]
