[info]
name = "hugo"
version = "0.75.0"
url = "https://gohugo.io/"
license = "Apache-2.0"

[discover]
binary = "hugo"
version_check.args = ["version"]
version_check.pattern = "^Hugo Static Site Generator v(\\d[^-]+)-[^/]+ "

[[install]]
download = "https://github.com/gohugoio/hugo/releases/download/v0.75.0/hugo_0.75.0_Linux-64bit.tar.gz"
checksums.sha256 = "3628614c0cdeefa4eb2530cd653c2d6084b5c68aaa65138790d680a40898b8c2"
files = [
  { source = "hugo", type = "binary" }
]
