[info]
name = "kubectl"
version = "1.19.0"
url = "https://kubernetes.io/docs/reference/kubectl/overview/"
license = "Apache-2.0"

[discover]
binary = "kubectl"
version_check.args = ["version", "--client=true", "--short=true"]
version_check.pattern = "Client Version: v(\\d\\S+)"

[[install]]
download = "https://dl.k8s.io/v1.19.0/kubernetes-client-linux-amd64.tar.gz"
checksums.sha512 = "1590d4357136a71a70172e32820c4a68430d1b94cf0ac941ea17695fbe0c5440d13e26e24a2e9ebdd360c231d4cd16ffffbbe5b577c898c78f7ebdc1d8d00fa3"
files = [
  { source = "kubernetes/client/bin/kubectl", type = "bin" }
]
