[info]
name = "mdcat"
version = "0.21.0"
url = "https://github.com/lunaryorn/mdcat"
license = "MPL-2.0"

[discover]
binary = "mdcat"
version_check.args = ["--version"]
version_check.pattern = "mdcat (\\d\\S+)"

[[install]]
download = "https://github.com/lunaryorn/mdcat/releases/download/mdcat-0.21.0/mdcat-0.21.0-x86_64-unknown-linux-musl.tar.gz"
checksums.b2 = "dd684b0c05eaecf28a3915789b855c9df8cfe7ad55f187dceb5713e78be766275672281aa3f2d7180e3ebd0c726ca69ccb6b05c0a97f7803ca027dc6d9bfec7f"
files = [
    { source = "mdcat-0.21.0-x86_64-unknown-linux-musl/mdcat", type = "bin" },
    { source = "mdcat-0.21.0-x86_64-unknown-linux-musl/completions/mdcat.fish", type = "completion", shell = "fish" },
]
