[info]
name = "mdcat"
version = "0.19.0"
url = "https://github.com/lunaryorn/mdcat"
license = "MPL-2.0"

[discover]
binary = "mdcat"
version_check.args = ["--version"]
version_check.pattern = "mdcat (\\d\\S+)"

[[install]]
download = "https://github.com/lunaryorn/mdcat/releases/download/mdcat-0.19.0/mdcat-0.19.0-x86_64-unknown-linux-musl.tar.gz"
checksums.b2 = "822d030885e4871ae19f59013095e07ba7c3d15ca209dd86b5506f3c50b07ae462f67f603d3e6f2d04a2d8b8ee5ea7951e7c9fc458ad2ed8f3d82e401cba26c4"
files = [
    { source = "mdcat-0.19.0-x86_64-unknown-linux-musl/mdcat", type = "bin" },
    { source = "mdcat-0.19.0-x86_64-unknown-linux-musl/completions/mdcat.fish", type = "completion", shell = "fish" },
]
