[info]
name = "mdcat"
version = "0.20.0"
url = "https://github.com/lunaryorn/mdcat"
license = "MPL-2.0"

[discover]
binary = "mdcat"
version_check.args = ["--version"]
version_check.pattern = "mdcat (\\d\\S+)"

[[install]]
download = "https://github.com/lunaryorn/mdcat/releases/download/mdcat-0.20.0/mdcat-0.20.0-x86_64-unknown-linux-musl.tar.gz"
checksums.b2 = "0cb0a6a9de22922d82fd6c5118f6c8736b11575148fc1401fdd7502df6fe281fe4f3a53d6d1ea0ec680960df27d5af1037a2ae5cbc69a44333e81f8dccfb8636"
files = [
    { source = "mdcat-0.20.0-x86_64-unknown-linux-musl/mdcat", type = "bin" },
    { source = "mdcat-0.20.0-x86_64-unknown-linux-musl/completions/mdcat.fish", type = "completion", shell = "fish" },
]
