[info]
name = "mdcat"
version = "0.22.2"
url = "https://github.com/lunaryorn/mdcat"
license = "MPL-2.0"

[discover]
binary = "mdcat"
version_check.args = ["--version"]
version_check.pattern = "mdcat (\\d\\S+)"

[[install]]
download = "https://github.com/lunaryorn/mdcat/releases/download/mdcat-0.22.2/mdcat-0.22.2-x86_64-unknown-linux-musl.tar.gz"
checksums.b2 = "f31fe78ef91a20d08858c5e3a2ace56a41dde24e9046f43f1b9cae205569fb5822acfa3a4709a825eb092c8bd62488223dca43f02ea651d8a62c103dcc1b36c1"
files = [
  { source = "mdcat-0.22.2-x86_64-unknown-linux-musl/mdcat", type = "bin", links=["mdless"] },
  { source = "mdcat-0.22.2-x86_64-unknown-linux-musl/completions/mdcat.fish", type = "completion", shell = "fish" },
]
