[info]
name = "minikube"
version = "1.12.3"
url = "https://github.com/kubernetes/minikube"
license = "Apache-2.0"

[discover]
binary = "minikube"
version_check.args = ["version"]
version_check.pattern = "minikube version: v(\\d\\S+)"

[[install]]
download = "https://github.com/kubernetes/minikube/releases/download/v1.12.3/minikube-linux-amd64"
checksums.sha256 = "664ebef01166ef6c6b13ff1d70faecca9292e2fcdc85766e8ebd2c607488711c"
name = "minikube"
type = "bin"

