[info]
name = "mmv"
version = "0.1.3"
url = "https://github.com/itchyny/mmv"
license = "MIT"

[discover]
binary = "mmv"
version_check.args = ["-version"]
version_check.pattern = "mmv (\\d\\S+) \\("

[[install]]
download = "https://github.com/itchyny/mmv/releases/download/v0.1.3/mmv_v0.1.3_linux_amd64.tar.gz"
checksums.b2 = "a7493568aa9197d25533a715c36097730fb424bb4354706b10789210f1eb5ff6a7d3183eaaa8b85e238b592201d94bb8e8e22764d765df75683a26e2f32527f7"
files = [
    { source = "mmv_v0.1.3_linux_amd64/mmv", type = "bin" }
]
