[info]
name = "oxipng"
version = "4.0.3"
url = "https://github.com/shssoichiro/oxipng"
license = "MIT"

[discover]
binary = "oxipng"
version_check.args = ["--version"]
version_check.pattern = "oxipng (\\d\\S+)"

[[install]]
download = "https://github.com/shssoichiro/oxipng/releases/download/v4.0.3/oxipng-4.0.3-x86_64-unknown-linux-musl.tar.gz"
checksums.b2 = "f07be7510b99c25953fa36fa4b1eed9f3b688b1b6a30b06b6794f3cc242e38015ba81e8946c292e81d2e5fe2deb043fd9b680f28963cb41a4cd7803eb47c8315"
files = [
  { source = "oxipng-4.0.3-x86_64-unknown-linux-musl/oxipng", type = "binary" }
]
