[info]
name = "oxipng"
version = "3.0.1"
url = "https://github.com/shssoichiro/oxipng"
license = "MIT"

[discover]
binary = "oxipng"
version_check.args = ["--version"]
version_check.pattern = "oxipng (\\d\\S+)"

[[install]]
download = "https://github.com/shssoichiro/oxipng/releases/download/v3.0.1/oxipng-3.0.1-x86_64-unknown-linux-musl.tar.gz"
checksums.b2 = "38be0055755b70074a14da047beb4b471d62720a0776d339e6fa7dba5dc7b38eaf41a39b76d6fddc1a2520bd5ddb8116642fabf47588139d4898271934a69b05"
files = [
  { source = "oxipng-3.0.1-x86_64-unknown-linux-musl/oxipng", type = "binary" }
]
