[info]
name = "oxipng"
version = "4.0.0"
url = "https://github.com/shssoichiro/oxipng"
license = "MIT"

[discover]
binary = "oxipng"
version_check.args = ["--version"]
version_check.pattern = "oxipng (\\d\\S+)"

[[install]]
download = "https://github.com/shssoichiro/oxipng/releases/download/v4.0.0/oxipng-4.0.0-x86_64-unknown-linux-musl.tar.gz"
checksums.b2 = "7af37b80098ae7a9e59aefa8f81aabe83b1dd176ab792cc849ae3dc346b258b89bc82a31cf582c7c7b1665a8148e59039520c239c73a1f1c82681edb71d79f89"
files = [
  { source = "oxipng-4.0.0-x86_64-unknown-linux-musl/oxipng", type = "binary" }
]
