[info]
name = "pandoc"
version = "2.11.4"
url = "https://pandoc.org"
license = "GPL-2.0-or-later"

[discover]
binary = "pandoc"
version_check.args = ["--version"]
version_check.pattern = "pandoc (\\d\\S+)"

[[install]]
download = "https://github.com/jgm/pandoc/releases/download/2.11.4/pandoc-2.11.4-linux-amd64.tar.gz"
checksums.b2 = "a6e526b9650a7bcad5012790a14efbf8cbb17974b29a798b9d6d8b400554bd6aa2aa1b540313c2984d3ccd8f42cc63cc3850f159ac0f1fe3946bba0fe6733f44"
files = [
    { source = "pandoc-2.11.4/bin/pandoc", type = "bin" },
    { source = "pandoc-2.11.4/share/man/man1/pandoc.1.gz", type = "man", section = 1 },
]

[remove]
additional_files = [
    # Extra citeproc is gone in newer pandoc releases
    { name = "pandoc-citeproc", type = "bin" },
    { name = "pandoc-citeproc.1.gz", type = "man", section = 1 }
]
