[info]
name = "procs"
version = "0.10.10"
url = "https://github.com/dalance/procs"
licence = "MIT"

[discover]
binary = "procs"
version_check.args = ["--version"]
version_check.pattern = "procs \"(\\d\\S+)"

[[install]]
download = "https://github.com/dalance/procs/releases/download/v0.10.10/procs-v0.10.10-x86_64-lnx.zip"
checksums.b2 = "43181c2b172e18c28ed1b57b37008d80d0839f7e5c6dc0cdc0d6ca8f963122c5aa043ea690fad05bab5d3ee041ff03b2e596abc7d6ec29b75708588c6778e1d9"
files = [
    { source = "procs", type = "binary" }
]