[info]
name = "procs"
version = "0.11.3"
url = "https://github.com/dalance/procs"
licence = "MIT"

[discover]
binary = "procs"
version_check.args = ["--version"]
version_check.pattern = "procs \"(\\d\\S+)"

[[install]]
download = "https://github.com/dalance/procs/releases/download/v0.11.3/procs-v0.11.3-x86_64-lnx.zip"
checksums.b2 = "b0afbc5a8be634d898e79827fd3d40379c29f12a0fbad55fc44306b12f46260a9af92167caae7023f98f640e0c5abca918531bc25317d90f263c8fc1ce014e37"
files = [
    { source = "procs", type = "binary" }
]
