[info]
name = "scalafmt"
version = "2.7.1"
url = "https://scalameta.org/scalafmt/"
license = "Apache-2.0"

[discover]
binary = "scalafmt"
version_check.args = ["--version"]
version_check.pattern = "scalafmt (\\d\\S+)"

[[install]]
download = "https://github.com/scalameta/scalafmt/releases/download/v2.7.1/scalafmt-linux-musl"
checksums.b2 = "d4a5aa969ef3ab173e92f9869c7da9cdd663e35b2a0b2365777a43e9efd135514d93a7d01b6b7bb11efa02cd9c53fe7a6105989312f9f4de9edd425f0dd26c9d"
type = "binary"
name = "scalafmt"
