[info]
name = "shfmt"
version = "3.2.2"
url = "https://github.com/mvdan/sh"
license = "BSD-3-Clause"

[discover]
binary = "shfmt"
version_check.args = ["-version"]
version_check.pattern = "v(\\d\\S+)"

[[install]]
download = "https://github.com/mvdan/sh/releases/download/v3.2.2/shfmt_v3.2.2_linux_amd64"
checksums.b2 = "d84a9004f70ffc4faf885c82388381dd8bf3900d2b369f034090ac0a7e656ba5440adbca0e5a3c51d202e4b0189a45e14a98159dbf5a1f9122fb47b35362dcb0"
name = "shfmt"
type = "bin"
