[info]
name = "shfmt"
version = "3.1.2"
url = "https://github.com/mvdan/sh"
license = "BSD-3-Clause"

[discover]
binary = "shfmt"
version_check.args = ["-version"]
version_check.pattern = "v(\\d\\S+)"

[[install]]
download = "https://github.com/mvdan/sh/releases/download/v3.1.2/shfmt_v3.1.2_linux_amd64"
checksums.b2 = "47d825ac5c2c4cff887f6d3e44512601a9243affa1ad2e4bb45cfd58b191edf968fed9ab97ae9d361471699a1d53b3038bc966a9b63efae363d35e6a86a4072e"
name = "shfmt"
type = "bin"
