[info]
name = "vivid"
version = "0.6.0"
url = "https://github.com/sharkdp/vivid"
license = "MIT OR Apache-2.0"

[discover]
binary = "vivid"
version_check.args = ["--version"]
version_check.pattern = "vivid (\\d\\S+)"

[[install]]
download = "https://github.com/sharkdp/vivid/releases/download/v0.6.0/vivid-v0.6.0-x86_64-unknown-linux-musl.tar.gz"
checksums.b2 = "0ecb66bcb6468f409014c41bc6ec9660dcb8204b0092abe0c80f408ec45112d501fcf990782fa8dda5dd715a5b10f8a6529315ba8498221f257509da09688fd4"
files = [
    { source = "vivid-v0.6.0-x86_64-unknown-linux-musl/vivid", type = "bin" },
]
