[info]
name = "youtube-dl"
version = "2021.01.08"
url = "https://github.com/ytdl-org/youtube-dl"
license = "Unlicense"

[discover]
binary = "youtube-dl"
version_check.args = ["--version"]
version_check.pattern = "(\\d\\S+)"

[[install]]
download = "https://github.com/ytdl-org/youtube-dl/releases/download/2021.01.08/youtube-dl"
checksums.sha512 = "5ca87d3118f6f642722bc8f05af77bf235450db67edc76ab1b362b46764df40eeda8192a5c154c4b7d5ffbb6d5a04da9367da1fadedc4466c41b4498d1e8dfac"
type = "bin"

[[install]]
download = "https://github.com/ytdl-org/youtube-dl/releases/download/2021.01.08/youtube-dl-2021.01.08.tar.gz"
checksums.sha512 = "516c5ac6e0e4513e574771a9d39f643f077e18b408dc7b709b92ca99d2d72f15719b545d5f7598a3a1d5eaeae52efff283c42001ce8c846c019582490be8cac1"
files = [
    { source = "youtube-dl/youtube-dl.1", type = "man", section = 1 },
    { source = "youtube-dl/youtube-dl.fish", type = "completion", shell = "fish" },
]
