[info]
name = "youtube-dl"
version = "2021.02.04.1"
url = "https://github.com/ytdl-org/youtube-dl"
license = "Unlicense"

[discover]
binary = "youtube-dl"
version_check.args = ["--version"]
version_check.pattern = "(\\d\\S+)"

[[install]]
download = "https://github.com/ytdl-org/youtube-dl/releases/download/2021.02.04.1/youtube-dl"
checksums.sha512 = "2e8983d6186402be41900cc3ef76c5758fda2086d2a535bd383935ef594bfce25552905515e1e4bf9218a9e46ec0944ab1ed2a68b54a11d5b5fd74d8dd46943d"
type = "bin"

[[install]]
download = "https://github.com/ytdl-org/youtube-dl/releases/download/2021.02.04.1/youtube-dl-2021.02.04.1.tar.gz"
checksums.sha512 = "b1050ace3adf1811adaa336d5b3574c938bf6fde1163e50b35c8a11bb5c251cf272ca5de3ff8132a44417ea2ced7b611c19e4aaf4dfd12adfeac03afe14df0dc"
files = [
    { source = "youtube-dl/youtube-dl.1", type = "man", section = 1 },
    { source = "youtube-dl/youtube-dl.fish", type = "completion", shell = "fish" },
]
