[info]
name = "youtube-dl"
version = "2020.12.31"
url = "https://github.com/ytdl-org/youtube-dl"
license = "Unlicense"

[discover]
binary = "youtube-dl"
version_check.args = ["--version"]
version_check.pattern = "(\\d\\S+)"

[[install]]
download = "https://github.com/ytdl-org/youtube-dl/releases/download/2020.12.31/youtube-dl"
checksums.sha512 = "3fe6b2da8875cc1a5edb0e55f6aa8434a03dd00e9c0a309d60d173e7bd44254dbe5421bb8280d7c4020f50f2193c0bde94febca4f6987180c1d6df02e97fbabd"
type = "bin"

[[install]]
download = "https://github.com/ytdl-org/youtube-dl/releases/download/2020.12.31/youtube-dl-2020.12.31.tar.gz"
checksums.sha512 = "78c69648f40c99581a533bac0e1afa2339f5681a01278f9234ad8b6b3f0f1b29e21bb669d27d0a6f9bccae0e3be954b571261d1ab9a1e778f3f028c8795595b6"
files = [
    { source = "youtube-dl/youtube-dl.1", type = "man", section = 1 },
    { source = "youtube-dl/youtube-dl.fish", type = "completion", shell = "fish" },
]
