name: Check manifests

on: [push, pull_request]

jobs:
  check-manifests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl -sSL --remote-name --remote-header-name "https://github.com/lunaryorn/homebins/releases/download/v0.2.0/homebins"
      - run: chmod 700 ./homebins
      - run: ./homebins manifest-list manifests/*.toml
